/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.BufferedReader;
import java.io.*;
import java.util.*;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicTreeUI;
import javax.swing.tree.*;
import javax.swing.plaf.basic.BasicTreeUI.*;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyledDocument;

/**
 *
 * @author hari
 */
public class NewJDialogBig extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialogBig
     */
    public NewJDialogBig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree5 = new javax.swing.JTree();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTree6 = new javax.swing.JTree();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTree7 = new javax.swing.JTree();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTree8 = new javax.swing.JTree();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTree9 = new javax.swing.JTree();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTree10 = new javax.swing.JTree();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTree11 = new javax.swing.JTree();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTree12 = new javax.swing.JTree();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTree13 = new javax.swing.JTree();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane5.setViewportView(jTextPane1);

        jTree5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree5MouseClicked(evt);
            }
        });
        jTree5.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree5ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTree5);

        jTree6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree6MouseClicked(evt);
            }
        });
        jTree6.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree6ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(jTree6);

        jTree7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTree7FocusGained(evt);
            }
        });
        jTree7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree7MouseClicked(evt);
            }
        });
        jTree7.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree7ValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(jTree7);

        jTextField1.setColumns(6);

        jTextField2.setColumns(9);

        jTextField3.setColumns(9);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("vxc");
        jLabel1.setToolTipText("");

        jButton2.setText("clear");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("snapshot");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("hhhh");

        jTree8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree8MouseClicked(evt);
            }
        });
        jTree8.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree8ValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(jTree8);

        jTree9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree9MouseClicked(evt);
            }
        });
        jTree9.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree9ValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(jTree9);

        jTree10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree10MouseClicked(evt);
            }
        });
        jTree10.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree10ValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(jTree10);

        jTree11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree11MouseClicked(evt);
            }
        });
        jTree11.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree11ValueChanged(evt);
            }
        });
        jScrollPane12.setViewportView(jTree11);

        jTree12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree12MouseClicked(evt);
            }
        });
        jTree12.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree12ValueChanged(evt);
            }
        });
        jScrollPane13.setViewportView(jTree12);

        jTree13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree13MouseClicked(evt);
            }
        });
        jTree13.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree13ValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(jTree13);

        jScrollPane6.setViewportView(jTextPane2);

        jScrollPane15.setViewportView(jTextPane3);

        jButton3.setText("clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(611, 611, 611)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2)))
                        .addGap(245, 245, 245))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String choice = "sun";
    public static String s1 = "";
    public static String s2 = "";
    public static String s3 = "";
    static NewJDialogBig dialog;
    //public static String file = "DasasR";
    public static String fileSuff = "";
    public static boolean dobAtrset=false;
    public static String dobAtr="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dialog.pack();
        dialog.setVisible(true);
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        s1 = dialog.jTextField1.getText();
        s2 = dialog.jTextField2.getText();
        s3 = dialog.jTextField3.getText();
        clear=true;
        ddest();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jLabel1.setText("search: "+s1+":"+s2+":"+s3+".");
                ddest2();
                ddest();
//                ddest();
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTree5ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree5ValueChanged
        // TODO add your handling code here:
        if(evt==null) return;
//        System.out.println("__"+evt.getPath().toString().length());
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
//        ddest();
//        System.out.println(":"+evt.getPath().toString().substring(6,evt.getPath().toString().length()-1)+":");
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
    }//GEN-LAST:event_jTree5ValueChanged

    private void jTree7ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree7ValueChanged
        // TODO add your handling code here:
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
//        ddest();
        
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
    }//GEN-LAST:event_jTree7ValueChanged

    private void jTree6ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree6ValueChanged
        // TODO add your handling code here:
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
//        ddest();
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
    }//GEN-LAST:event_jTree6ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dialog.pack();
        dialog.setVisible(true);
        dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        dialog.jTextField1.setText("");
//        dialog.jTextField2.setText("");
//        dialog.jTextField3.setText("");
        s1 = "";//dialog.jTextField1.getText();
        s2 = "";//dialog.jTextField2.getText();
        s3 = "";//dialog.jTextField3.getText();
        clear=true;
        //dialog.jLabel1.setText("");
        ddest();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jLabel1.setText("");
                ddest2();
                ddest();
//                ddest();
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        File f1= new File("snapshot.txt");
        File f2= new File("snapshot.html");
        try{
            if(!f1.exists())f1.createNewFile();
            if(!f2.exists())f1.createNewFile();
            PrintWriter p1=new PrintWriter(new FileWriter(f1,true));
            PrintWriter p2=new PrintWriter(new FileWriter(f2,true));
            p2.println("<html><body>");
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");
            Date dt= new Date();
            p1.println("\n\n----------"+sdf.format(dt)+"----------"+dobAtr+"----------");
            p1.println(jLabel1.getText());
            p1.println(jTextPane1.getText());
            p1.println(jTextPane3.getText());
            p1.println(jTextPane2.getText());
            p2.println("<br/><br/><font size=-1>\n\n----------"+sdf.format(dt)+"--------"+dobAtr+"--------</font>".replace("\n", "\n<br/>"));
            p2.println("<br/><b>"+jLabel1.getText()+"</b>");
//            if(jLabel1.getText().length()==0) {
//                if(jTextField1.getText().length()>0){
//                    p2.println("<br/><p>search1:"+jTextField1.getText()+"</p>");
//                    p1.println("search1:"+jTextField1.getText()+"");
//                }
//                if(jTextField2.getText().length()>0){
//                    p2.println("<br/><p>search2:"+jTextField2.getText()+"</p>");
//                    p1.println("search2:"+jTextField2.getText()+"");
//                }
//                if(jTextField3.getText().length()>0){
//                    p2.println("<br/><p>search2:"+jTextField3.getText()+"</p>");
//                    p1.println("search3:"+jTextField3.getText()+"");
//
//                }
//            }
            p2.println("<br/><font size=-2>"+jTextPane1.getText().replace("\n", "\n<br/>")+"</font>");
            p2.println("<br/><font size=-2>"+jTextPane3.getText().replace("\n", "\n<br/>")+"</font>");
            p2.println("<br/><font size=-2>"+jTextPane2.getText().replace("\n", "\n<br/>")+"</font>");
            p1.close();
            p2.close();
            
            
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTree8ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree8ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree8ValueChanged

    private void jTree9ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree9ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree9ValueChanged

    private void jTree10ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree10ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree10ValueChanged

    private void jTree11ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree11ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree11ValueChanged

    private void jTree12ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree12ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree12ValueChanged

    private void jTree13ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree13ValueChanged
        if(evt==null) return;
        ddest3(evt.getPath().toString().substring(1,4),evt.getPath().toString().substring(5,evt.getPath().toString().length()-1));
        jLabel1.setText(evt.getPath().toString().substring(1,evt.getPath().toString().length()-1));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree13ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            dialog.jTextPane1.setText("");
            dialog.jTextPane2.setText("");
            dialog.jTextPane3.setText("");
            clear=true;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTree7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree7MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
            TreePath tp = dialog.jTree7.getPathForLocation(evt.getX(), evt.getY());
            ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
            jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
        
    }//GEN-LAST:event_jTree7MouseClicked

    private void jTree7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree7FocusGained
        // TODO add your handling code here:
//        evt.get
    }//GEN-LAST:event_jTree7FocusGained

    private void jTree5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree5MouseClicked
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree5.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree5MouseClicked

    private void jTree6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree6MouseClicked
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree6.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree6MouseClicked

    private void jTree10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree10MouseClicked
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree10.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree10MouseClicked

    private void jTree8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree8MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree8.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree8MouseClicked

    private void jTree9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree9MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree9.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree9MouseClicked

    private void jTree12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree12MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree12.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree12MouseClicked

    private void jTree13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree13MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree13.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree13MouseClicked

    private void jTree11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree11MouseClicked
        // TODO add your handling code here:
        if(evt==null) return;
        try{
        TreePath tp = dialog.jTree11.getPathForLocation(evt.getX(), evt.getY());
        ddest3(tp.toString().substring(1,4),tp.toString().substring(5,tp.toString().length()-1));
        jLabel1.setText(tp.toString().substring(1,tp.toString().length()-1));
        }catch(Exception e){
        }
    }//GEN-LAST:event_jTree11MouseClicked

    /**
     * @param args the command line arguments
     */
    static int y1, y2;
    static boolean strict=true,clear=true;

    public static void main(String args[]) {
        if (args.length > 0) {
            fileSuff = args[0];
        }
        if (args.length > 1) {
            if(!args[1].startsWith("t"))strict=false;
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialogBig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialogBig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialogBig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialogBig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog = new NewJDialogBig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }

                });

//                BasicTreeUI.TreeSelectionHandler th= new BasicTreeUI.TreeSelectionHandler();
//                    dialog.jTree5.addTreeSelectionListener(new BasicTreeUI.{
//        
//    });
                ddest2();
                ddest();
            }
        });

    }

    public static void ddest2() {
        try {
            clear=true;
            BufferedReader br1 = new BufferedReader(new InputStreamReader(new FileInputStream("Meps"+fileSuff)));
            String line = "", str = "";
            ArrayList<String> as= new ArrayList<String>();
            while ((line = br1.readLine()) != null) {
                if (line.contains(",") || line.contains("Nmoo") || line.contains("Nmer") || line.contains("Nmar") || line.contains("Nven") || line.contains("Njup")  || line.contains("Nrah") || line.contains("Nsat")) {
                    if ((line.contains(s1)) && (line.contains(s2)) && (line.contains(s3))) {
//                        str += line + "\n";
                        if(line.length()>75)
                            line=line.substring(0,75);
                        as.add(line);
                    }
                }
            }
            br1.close();
//                     StyledDocument sd = new DefaultStyledDocument();
//                     sd.insertString(0, str, null);
//                     dialog.jTextPane1=new JTextPane(sd);
            String str1 = "",str2="",str3="";
            int ii=as.size(); int cn=0;
            for(String st:as){
                cn++;
                if(cn<11 || cn<ii/3){
                    if(st.length()>75)
                        st=st.substring(0,75);

                    str1+=st+"\n";
                }else if(cn<21 || ((cn>=ii/3) && (cn<2*ii/3))){
                    if(st.length()>75)
                        st=st.substring(0,75);
                    str2+=st+"\n";
                }else {
                    if(st.length()>75)
                        st=st.substring(0,75);
                    str3+=st+"\n";
                }
            }
//                     StyledDocument sd = new DefaultStyledDocument();
//                     sd.insertString(0, str, null);
//                     dialog.jTextPane1=new JTextPane(sd);
            dialog.jTextPane1.setText(str1);
            dialog.jTextPane2.setText(str3);
            dialog.jTextPane3.setText(str2);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void ddest3(String pre,String lab) {
//        System.out.println("--"+lab+"--");
        try {
            ArrayList<String> as= new ArrayList<String>();
            if(clear)clear=false;
            else{
                String s1=dialog.jTextPane1.getText();
                String s3=dialog.jTextPane2.getText();
                String s2=dialog.jTextPane3.getText();
                StringTokenizer stk=new StringTokenizer(s1,"\n");
                String sr="";
                while(stk.hasMoreTokens()){
                    sr=stk.nextToken();
                    if(sr.length()>75)
                        sr=sr.substring(0,75);
                    as.add(sr);
                }
                 stk=new StringTokenizer(s2,"\n");
                while(stk.hasMoreTokens()){
                    sr=stk.nextToken();
                    if(sr.length()>75)
                        sr=sr.substring(0,75);
                    as.add(sr);
                }
                stk=new StringTokenizer(s3,"\n");
                while(stk.hasMoreTokens()){
                    sr=stk.nextToken();
                    if(sr.length()>75)
                        sr=sr.substring(0,75);
                    as.add(sr);
                }
                if(!sr.startsWith("----"))
                    as.add("-------------");
            }
//            if(!as.get(as.size()).startsWith("-----"))
//            ArrayList<String> as= new ArrayList<String>();
            if(strict){
                if(pre.equals("Rah"))
                   pre="rah";
                if(pre.equals("Ket"))
                   pre="rah";
                if(pre.equals("Sun"))
                    pre=",";
                else
                    pre="N"+pre.toLowerCase();
            }else pre=" ";
            String[] sts=new String[7];
            StringTokenizer stk=new StringTokenizer(lab,",");
            int i=0;
            while((stk.hasMoreTokens())){
                sts[i]=stk.nextToken().substring(1,4); 
                if(sts[i].equals("Rah"))sts[i]="Rah";
//                System.out.print(":"+sts[i]+":");
                i++;
            }
//            System.out.println("=="+pre+"==");
            ArrayList<String> as2= new ArrayList<String>();
            String str1 = "",str2="",str3="";
            for(i=1;i<7;i++){
                BufferedReader br1 = new BufferedReader(new InputStreamReader(new FileInputStream("Meps"+fileSuff)));
                            String line = "";
                while ((line = br1.readLine()) != null) {
                    if(line.length()>75)
                        line=line.substring(0,75);
                    if(sts[i]==null || sts[i].length()==0){
                        if(i==1){
                            if(sts[0].length()>0 && line.contains(sts[0]) && line.contains("Asc") &&line.contains(pre))
                            {
                                   if(!as2.contains(line)){
                                       as2.add(line);
                                       as.remove(line);
                                   }
//                                str += line + "\n";
                            }
                            
                        }
                        continue;
                    }
                    if((line.contains(sts[i])&& line.indexOf(sts[i],line.indexOf(sts[i])+1)>0)&&line.contains(pre))
                    {
                                   if(!as2.contains(line)){
                                       as2.add(line);
                                       as.remove(line);
                                   }
//                            str += line + "\n";
                    }else
                    if(sts[i].equals(sts[i-1])){
                        if(line.contains(sts[i]) && line.contains("Asc")&&line.contains(pre))
                                   if(!as2.contains(line)){
                                       as2.add(line);
                                        as.remove(line);
                                   }

//                            str += line + "\n";
                    }else
                    if (((line.contains(sts[i]) && line.contains(sts[i-1]))||(line.contains("Asc") && line.contains(sts[i-1]))||(line.contains(sts[i]) && line.contains("Asc")))&&line.contains(pre)) {
                        
                                   if(!as2.contains(line)){
                                       as2.add(line);
                                       as.remove(line);
                                   }
                            
//                            str += line + "\n";
                    }
                }
                br1.close();
            }
            int ii=0; int cn=0;
            as.addAll(as2);String yy="";
            ArrayList<String> as3= new ArrayList<String>();
            for(String st:as){
                if(!yy.equals(st)){
                    as3.add(st);
                    yy=st;
                }
            }
            ii=as3.size();int i0=0;
            if(ii>50) i0=ii-50;
            for(String st:as3){
                cn++;
                if(cn<i0)continue;
                if(cn<11 || cn<(ii-i0)/3){
                    str1+=st+"\n";
                }else if(cn<21 || cn<2*(ii-i0)/3){
                    str2+=st+"\n";
                }else
                    str3+=st+"\n";
            }
//                     StyledDocument sd = new DefaultStyledDocument();
//                     sd.insertString(0, str, null);
//                     dialog.jTextPane1=new JTextPane(sd);
            dialog.jTextPane1.setText(str1);
            dialog.jTextPane2.setText(str3);
            dialog.jTextPane3.setText(str2);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void ddest() {
        /*try {
            BufferedReader br1 = new BufferedReader(new InputStreamReader(new FileInputStream("Meps"+fileSuff)));
            String line = "", str = "";
            while ((line = br1.readLine()) != null) {
                if (line.contains(",") || line.contains("Nmoo") || line.contains("Nmer") || line.contains("Nmar") || line.contains("Nven") || line.contains("Njup")  || line.contains("Nrah") || line.contains("Nsat")) {
                    if ((line.contains(s1)) && (line.contains(s2)) && (line.contains(s3))) {
                        str += line + "\n";
                    }
                }
            }
            br1.close();
//                     StyledDocument sd = new DefaultStyledDocument();
//                     sd.insertString(0, str, null);
//                     dialog.jTextPane1=new JTextPane(sd);
            dialog.jTextPane1.setText(str);

        } catch (Exception e) {
            e.printStackTrace();
        }*/
        
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
        DefaultMutableTreeNode root1 = null;
        DefaultMutableTreeNode root2 = null;
        DefaultMutableTreeNode root3 = null;
        DefaultMutableTreeNode root4 = null;
        DefaultMutableTreeNode root5 = null;
        DefaultMutableTreeNode root6 = null;
        DefaultMutableTreeNode root7 = null;
        DefaultMutableTreeNode root8 = null;
        DefaultMutableTreeNode root9 = null;
        //create the child nodes
        DefaultMutableTreeNode child1 = new DefaultMutableTreeNode("Child 1");
        DefaultMutableTreeNode child2 = new DefaultMutableTreeNode("Child 2");
        for (int i = 0; i < 100; i++) {
            root.add(new DefaultMutableTreeNode("Child -" + i));
        }
        root.add(child1);
        root.add(child2);
        try {
            BufferedReader br1 = new BufferedReader(new InputStreamReader(new FileInputStream("DasasR"+fileSuff)));
            String line = "", fl = "", FL2 = "", FL3 = "", FL4 = "";
            DefaultMutableTreeNode lev1 = new DefaultMutableTreeNode("");
            DefaultMutableTreeNode lev2 = new DefaultMutableTreeNode("");//null;
            DefaultMutableTreeNode lev3 = new DefaultMutableTreeNode("");//null;
            DefaultMutableTreeNode childa = new DefaultMutableTreeNode("");//null;
            DefaultMutableTreeNode childb = new DefaultMutableTreeNode("");//null;
            DefaultMutableTreeNode childc = new DefaultMutableTreeNode("");//null;
            DefaultMutableTreeNode childd = new DefaultMutableTreeNode("");//null;
            String slab = "", slab2 = "", stemp = "";
            while ((line = br1.readLine()) != null) {
                if(!dobAtrset){
                    if(line.contains(" dasa")){
                        StringTokenizer stk= new StringTokenizer(line);
                        stk.nextToken();stk.nextToken();stk.nextToken();stk.nextToken();stk.nextToken();
                        String dt=stk.nextToken();
                        dt+=" "+stk.nextToken();
                        dt+=" "+stk.nextToken();
                        dialog.jLabel2.setText(dt);
                        dobAtr=dt;
                        dobAtrset=true;
                    }
                }
                if (line.startsWith("sun-")) {
                    stemp = line;
                }
//                if (choice.equals("sun")) {
                    if (line.contains("SUN VD")) {
                        fl = "sun";
                        slab += stemp + " - Sun\n";
                        root1 = new DefaultMutableTreeNode("Sun");
                    } else if (line.contains("MOO VD")) {
                        fl = "moo";
                        slab += stemp + " - Moo\n";
                        root2 = new DefaultMutableTreeNode("Moo");
                    } else if (line.contains("MAR VD")) {
                        fl = "mar";
                        slab += stemp + " - Mar\n";
                        root3 = new DefaultMutableTreeNode("Mar");
//                    } else if (line.contains("VD")) {
//                        fl = "";
                    }
//                } else if (choice.equals("mer")) {
                    else if (line.contains("MER VD")) {
                        fl = "mer";
                        slab += stemp + " - Mer\n";
                        root4 = new DefaultMutableTreeNode("Mer");
                    } else if (line.contains("JUP VD")) {
                        fl = "jup";
                        slab += stemp + " - Jup\n";
                        root5 = new DefaultMutableTreeNode("Jup");
                    } else if (line.contains("VEN VD")) {
                        fl = "ven";
                        slab2 += stemp + " - Ven\n";
                        root6 = new DefaultMutableTreeNode("Ven");
//                    } else if (line.contains("VD")) {
//                        fl = "";
                    }
//                } else if (choice.equals("sat")) {
                    else if (line.contains("SAT VD")) {
                        fl = "sat";
                        slab2 += stemp + " - Sat\n";
                        root7 = new DefaultMutableTreeNode("Sat");
                    } else if (line.contains("RAH VD")) {
                        fl = "rah";
                        slab2 += stemp + " - Rah\n";
                        root8 = new DefaultMutableTreeNode("Rah");
                    } else if (line.contains("KET VD")) {
                        fl = "ket";
                        slab2 += stemp + " - Ket";
                        root9 = new DefaultMutableTreeNode("Ket");
//                    } else if (line.contains("VD")) {
//                        fl = "";
                    }
                    else if (line.contains("VD")) 
                        fl = "";
//                }

                if (fl.equals("")) {
                    continue;
                }
                if (line.startsWith("Sun") || line.startsWith("Moo") || line.startsWith("Mar") || line.startsWith("Mer") || line.startsWith("Ven") || line.startsWith("Jup") || line.startsWith("Sat") || line.startsWith("Rah") || line.startsWith("Ket")) {
                    FL2 = line.substring(0, 3);
                    if (line.indexOf("*") > 0) {
                        int k1 = line.indexOf("*");
                        int k2 = line.indexOf("-", k1 + 1);
                        int k3 = line.indexOf(":", k2 + 1);
                        int k4 = line.indexOf("-", k3 + 1);
                        String y1 = line.substring(k1 + 1, k2+6).trim();
                        String y2 = line.substring(k3 + 1, k4+6).trim();
//                                DefaultMutableTreeNode childa = new DefaultMutableTreeNode("Sun " + y1 + ":" + y2);
                        lev1 = new DefaultMutableTreeNode(FL2 + " " + y1 + " :: " + y2);
                        if (fl.equals("sun")) {
                            root1.add(lev1);
                        }
                        if (fl.equals("moo")) {
                            root2.add(lev1);
                        }
                        if (fl.equals("mar")) {
                            root3.add(lev1);
                        }
                        if (fl.equals("mer")) {
                            root4.add(lev1);
                        }
                        if (fl.equals("jup")) {
                            root5.add(lev1);
                        }
                        if (fl.equals("ven")) {
                            root6.add(lev1);
                        }
                        if (fl.equals("sat")) {
                            root7.add(lev1);
                        }
                        if (fl.equals("rah")) {
                            root8.add(lev1);
                        }
                        if (fl.equals("ket")) {
                            root9.add(lev1);
                        }
                    }

                }

                if (line.startsWith("    Sun") || line.startsWith("    Moo") || line.startsWith("    Mar") || line.startsWith("    Mer") || line.startsWith("    Ven") || line.startsWith("    Jup") || line.startsWith("    Sat") || line.startsWith("    Rah") || line.startsWith("    Ket")) {
                    if (line.indexOf("*") > 0) {
                        int k1 = line.indexOf("*");
                        int k2 = line.indexOf("-", k1 + 1);
//                                int k22 = line.indexOf("-", k2 + 1);
                        int k3 = line.indexOf(":", k2 + 1);
                        int k4 = line.indexOf("-", k3 + 1);
//                                int k44 = line.indexOf("-", k4 + 1);
                        String y1 = line.substring(k1 + 1, k2 + 6).trim();
                        String y2 = line.substring(k3 + 1, k4 + 6).trim();
//                                int y1 = Integer.parseInt(line.substring(k1 + 1, k2).trim());
//                                int y2 = Integer.parseInt(line.substring(k3 + 1, k4).trim());
                        childa = new DefaultMutableTreeNode(line.substring(4, 7) + " " + y1 + " :: " + y2);
//                                if(FL2.equals("Sun"))
//                                    lev1.add(childa);
//                                if(FL2.equals("Moo"))
//                                    lev1.add(childa);
//                                if(FL2.equals("Mar"))
                        lev1.add(childa);
                    }

                }

                if (line.startsWith("        Sun") || line.startsWith("        Moo") || line.startsWith("        Mar") || line.startsWith("        Mer") || line.startsWith("        Ven") || line.startsWith("        Jup") || line.startsWith("        Sat") || line.startsWith("        Rah") || line.startsWith("        Ket")) {
                    if (line.indexOf("*") > 0) {
                        int k1 = line.indexOf("*");
                        int k2 = line.indexOf("-", k1 + 1);
                        int k3 = line.indexOf(":", k2 + 1);
                        int k4 = line.indexOf("-", k3 + 1);
                        String y1 = line.substring(k1 + 1, k2 + 6).trim();
                        String y2 = line.substring(k3 + 1, k4 + 6).trim();
                        childb = new DefaultMutableTreeNode(line.substring(8, 11) + " " + y1 + " :: " + y2);
                        childa.add(childb);
                    }

                }

                if (line.startsWith("            Sun") || line.startsWith("            Moo") || line.startsWith("            Mar") || line.startsWith("            Mer") || line.startsWith("            Ven") || line.startsWith("            Jup") || line.startsWith("            Sat") || line.startsWith("            Rah") || line.startsWith("            Ket")) {
                    if (line.indexOf("*") > 0) {
                        int k1 = line.indexOf("*");
                        int k2 = line.indexOf("-", k1 + 1);
                        int k3 = line.indexOf(":", k2 + 1);
                        int k4 = line.indexOf("-", k3 + 1);
                        String y1 = line.substring(k1 + 1, k2 + 12).trim();
                        String y2 = line.substring(k3 + 1, k4 + 12).trim();
                        childc = new DefaultMutableTreeNode(line.substring(12, 15) + " " + y1 + " :: " + y2);
                        childb.add(childc);
                    }

                }

                if (line.startsWith("                Sun") || line.startsWith("                Moo") || line.startsWith("                Mar") || line.startsWith("                Mer") || line.startsWith("                Ven") || line.startsWith("                Jup") || line.startsWith("                Sat") || line.startsWith("                Rah") || line.startsWith("                Ket")) {
                    if (line.indexOf("*") > 0) {
                        int k1 = line.indexOf("*");
                        int k2 = line.indexOf("-", k1 + 1);
                        int k3 = line.indexOf(":", k2 + 1);
                        int k4 = line.indexOf("-", k3 + 1);
                        String y1 = line.substring(k1 + 1, k2 + 12).trim();
                        String y2 = line.substring(k3 + 1, k4 + 12).trim();
                        childd = new DefaultMutableTreeNode(line.substring(16, 19) + " " + y1 + " :: " + y2);
                        childc.add(childd);
                    }

                }


                
            }
            br1.close();
            dialog.jTextArea1.setText(slab2);
            dialog.jTextArea2.setText(slab);

        } catch (Exception e) {
            e.printStackTrace();
        }

        DefaultTreeModel model;
        DefaultTreeModel model1 = (DefaultTreeModel) dialog.jTree5.getModel();
        model1.setRoot(root1);
        DefaultTreeModel model2 = (DefaultTreeModel) dialog.jTree6.getModel();
        model2.setRoot(root2);
        DefaultTreeModel model3 = (DefaultTreeModel) dialog.jTree7.getModel();
        model3.setRoot(root3);
        DefaultTreeModel model4 = (DefaultTreeModel) dialog.jTree8.getModel();
        model4.setRoot(root4);
        DefaultTreeModel model5 = (DefaultTreeModel) dialog.jTree9.getModel();
        model5.setRoot(root5);
        DefaultTreeModel model6 = (DefaultTreeModel) dialog.jTree10.getModel();
        model6.setRoot(root6);
        DefaultTreeModel model7 = (DefaultTreeModel) dialog.jTree11.getModel();
        model7.setRoot(root7);
        DefaultTreeModel model8 = (DefaultTreeModel) dialog.jTree12.getModel();
        model8.setRoot(root8);
        DefaultTreeModel model9 = (DefaultTreeModel) dialog.jTree13.getModel();
        model9.setRoot(root9);
        dialog.pack();
        dialog.show();
        dialog.setVisible(true);

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTree jTree10;
    private javax.swing.JTree jTree11;
    private javax.swing.JTree jTree12;
    private javax.swing.JTree jTree13;
    private javax.swing.JTree jTree5;
    private javax.swing.JTree jTree6;
    private javax.swing.JTree jTree7;
    private javax.swing.JTree jTree8;
    private javax.swing.JTree jTree9;
    // End of variables declaration//GEN-END:variables
}
